version: '3.7'

services:
  
  db:
    image: kartoza/postgis:12.0
    volumes:
      - foody_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,pg_trgm,unaccent
    ports:
      - 5432:5432
    restart: always
  
    
  web:
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && pytest" 
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
     

volumes:
  foody_data:
